quarkus.datasource.db-kind=oracle
quarkus.datasource.username=${DBUSERNAME}
quarkus.datasource.password=${DBPASSWD}
quarkus.datasource.jdbc.url=${JDBCURL}
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.sql-load-script=no-file